import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mobibo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <ConfigProvider
        theme={{
          components: {
            Modal: {
              contentBg: "#e4e4e4",
            },
          },
        }}
      >
        <body>
          <Header />
          <main className={inter.className}>{children}</main>
          <Footer />
        </body>
      </ConfigProvider>
    </html>
  );
}
