import { Inter } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mobibo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
       <ConfigProvider
    theme={{
      components: {
        Modal: {
          contentBg	: "#e4e4e4"
        },
      },
    }}>
      <body className={inter.className}>{children}</body>
      </ConfigProvider>
    </html>
  );
}
